// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: student_payment.proto

package schedule_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StudentPaymentService_Create_FullMethodName  = "/schedule_service.StudentPaymentService/Create"
	StudentPaymentService_GetByID_FullMethodName = "/schedule_service.StudentPaymentService/GetByID"
	StudentPaymentService_GetList_FullMethodName = "/schedule_service.StudentPaymentService/GetList"
	StudentPaymentService_Update_FullMethodName  = "/schedule_service.StudentPaymentService/Update"
	StudentPaymentService_Delete_FullMethodName  = "/schedule_service.StudentPaymentService/Delete"
)

// StudentPaymentServiceClient is the client API for StudentPaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentPaymentServiceClient interface {
	Create(ctx context.Context, in *CreateStudentPayment, opts ...grpc.CallOption) (*GetStudentPayment, error)
	GetByID(ctx context.Context, in *StudentPaymentPrimaryKey, opts ...grpc.CallOption) (*GetStudentPayment, error)
	GetList(ctx context.Context, in *GetListStudentPaymentRequest, opts ...grpc.CallOption) (*GetListStudentPaymentResponse, error)
	Update(ctx context.Context, in *UpdateStudentPayment, opts ...grpc.CallOption) (*GetStudentPayment, error)
	Delete(ctx context.Context, in *StudentPaymentPrimaryKey, opts ...grpc.CallOption) (*EmptyStudentPayment, error)
}

type studentPaymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentPaymentServiceClient(cc grpc.ClientConnInterface) StudentPaymentServiceClient {
	return &studentPaymentServiceClient{cc}
}

func (c *studentPaymentServiceClient) Create(ctx context.Context, in *CreateStudentPayment, opts ...grpc.CallOption) (*GetStudentPayment, error) {
	out := new(GetStudentPayment)
	err := c.cc.Invoke(ctx, StudentPaymentService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentPaymentServiceClient) GetByID(ctx context.Context, in *StudentPaymentPrimaryKey, opts ...grpc.CallOption) (*GetStudentPayment, error) {
	out := new(GetStudentPayment)
	err := c.cc.Invoke(ctx, StudentPaymentService_GetByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentPaymentServiceClient) GetList(ctx context.Context, in *GetListStudentPaymentRequest, opts ...grpc.CallOption) (*GetListStudentPaymentResponse, error) {
	out := new(GetListStudentPaymentResponse)
	err := c.cc.Invoke(ctx, StudentPaymentService_GetList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentPaymentServiceClient) Update(ctx context.Context, in *UpdateStudentPayment, opts ...grpc.CallOption) (*GetStudentPayment, error) {
	out := new(GetStudentPayment)
	err := c.cc.Invoke(ctx, StudentPaymentService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentPaymentServiceClient) Delete(ctx context.Context, in *StudentPaymentPrimaryKey, opts ...grpc.CallOption) (*EmptyStudentPayment, error) {
	out := new(EmptyStudentPayment)
	err := c.cc.Invoke(ctx, StudentPaymentService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentPaymentServiceServer is the server API for StudentPaymentService service.
// All implementations should embed UnimplementedStudentPaymentServiceServer
// for forward compatibility
type StudentPaymentServiceServer interface {
	Create(context.Context, *CreateStudentPayment) (*GetStudentPayment, error)
	GetByID(context.Context, *StudentPaymentPrimaryKey) (*GetStudentPayment, error)
	GetList(context.Context, *GetListStudentPaymentRequest) (*GetListStudentPaymentResponse, error)
	Update(context.Context, *UpdateStudentPayment) (*GetStudentPayment, error)
	Delete(context.Context, *StudentPaymentPrimaryKey) (*EmptyStudentPayment, error)
}

// UnimplementedStudentPaymentServiceServer should be embedded to have forward compatible implementations.
type UnimplementedStudentPaymentServiceServer struct {
}

func (UnimplementedStudentPaymentServiceServer) Create(context.Context, *CreateStudentPayment) (*GetStudentPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedStudentPaymentServiceServer) GetByID(context.Context, *StudentPaymentPrimaryKey) (*GetStudentPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedStudentPaymentServiceServer) GetList(context.Context, *GetListStudentPaymentRequest) (*GetListStudentPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedStudentPaymentServiceServer) Update(context.Context, *UpdateStudentPayment) (*GetStudentPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedStudentPaymentServiceServer) Delete(context.Context, *StudentPaymentPrimaryKey) (*EmptyStudentPayment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

// UnsafeStudentPaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentPaymentServiceServer will
// result in compilation errors.
type UnsafeStudentPaymentServiceServer interface {
	mustEmbedUnimplementedStudentPaymentServiceServer()
}

func RegisterStudentPaymentServiceServer(s grpc.ServiceRegistrar, srv StudentPaymentServiceServer) {
	s.RegisterService(&StudentPaymentService_ServiceDesc, srv)
}

func _StudentPaymentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentPayment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentPaymentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentPaymentService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentPaymentServiceServer).Create(ctx, req.(*CreateStudentPayment))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentPaymentService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentPaymentPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentPaymentServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentPaymentService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentPaymentServiceServer).GetByID(ctx, req.(*StudentPaymentPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentPaymentService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListStudentPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentPaymentServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentPaymentService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentPaymentServiceServer).GetList(ctx, req.(*GetListStudentPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentPaymentService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentPayment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentPaymentServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentPaymentService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentPaymentServiceServer).Update(ctx, req.(*UpdateStudentPayment))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentPaymentService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentPaymentPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentPaymentServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentPaymentService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentPaymentServiceServer).Delete(ctx, req.(*StudentPaymentPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentPaymentService_ServiceDesc is the grpc.ServiceDesc for StudentPaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentPaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedule_service.StudentPaymentService",
	HandlerType: (*StudentPaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _StudentPaymentService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _StudentPaymentService_GetByID_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _StudentPaymentService_GetList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _StudentPaymentService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StudentPaymentService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student_payment.proto",
}
